#!/bin/ksh

# Script to sum up DOS files from VASP
# Modified by Yashpal Singh, EEWS, KAIST on 8th March 2017: according to modified  split_dos LORBIT=11
#Modified on 15 Oct 2021 for summing non-colinear dos

if [ $# -lt 3 ]; then
	echo "Usage: sum_dos [0] [start] [end]"
	echo "Or: sum_dos [1] [i] [j] [k] [l] ..."
	exit 1
fi


type=$1
shift 1

# Contiguous
if [ $type -eq 0 ]; then

	start=$1
	end=$2
	shift 2
	string=$start.to.$end

	echo $start
	echo $end


# First file
	i=$start
	nl=$(wc -l DOS$i | sed 's/://g' | awk '{print $1}')
echo $nl

 sed -n '2,'$nl' p' DOS$i | awk '{printf "%12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f \n", $1, $2, $6, $10, $14, $18, $22, $26, $30, $34, $6+$10+$14, $18+$22+$26+$30+$34}' >| DOS.tmp
# E, s,py,pz,px,dxy,dyz,dz2,dxz,dx2,py+px+pz,dxy+dyz+dz2+dxz+dx2,total
#E, s,3 componenets of s, py, 3 components of py, and so on....

	i=$((i+1))

	while [ $i -le $end ]; do

 sed -n '2,'$nl' p' DOS$i | awk '{printf "%12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f \n", $1, $2, $6, $10, $14, $18, $22, $26, $30, $34, $6+$10+$14, $18+$22+$26+$30+$34}' >| DOS.tmp2

# E, s,py,pz,px,dxy,dyz,dz2,dxz,dx2,py+px+pz,dxy+dyz+dz2+dxz+dx2,total

		paste DOS.tmp DOS.tmp2 | awk '{printf "%15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f \n", $1, $2+$14, $3+$15, $4+$16, $5+$17, $6+$18, $7+$19, $8+$20, $9+$21, $10+$22, $11+$23, $12+$24}' >| DOS.tmp3

		mv -f DOS.tmp3 DOS.tmp

		i=$((i+1))

	done


else

	start=$1
	shift 1

# First file
	i=$start
	nl=$(wc -l DOS$i | sed 's/://g' | awk '{print $1}')
	echo $nl

 sed -n '2,'$nl' p' DOS$i | awk '{printf "%12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f \n", $1, $2, $6, $10, $14, $18, $22, $26, $30, $34, $6+$10+$14, $18+$22+$26+$30+$34}' >| DOS.tmp
# E, s,py,pz,px,dxy,dyz,dz2,dxz,dx2,py+px+pz,dxy+dyz+dz2+dxz+dx2,total

	string=$start
	for i in "$@"; do

		echo $i
		string=$(echo $string.$i)
 sed -n '2,'$nl' p' DOS$i | awk '{printf "%12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f %12.8f \n", $1, $2, $6, $10, $14, $18, $22, $26, $30, $34, $6+$10+$14, $18+$22+$26+$30+$34}' >| DOS.tmp2

		paste DOS.tmp DOS.tmp2 | awk '{printf "%15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f %15.8f \n", $1, $2+$14, $3+$15, $4+$16, $5+$17, $6+$18, $7+$19, $8+$20, $9+$21, $10+$22, $11+$23, $12+$24}' >| DOS.tmp3

		mv -f DOS.tmp3 DOS.tmp
	done

fi


mv DOS.tmp DOS.SUM.$string
rm -f DOS.tmp2

exit 0

